export const FETCH_EMPLOYEES_STARTED = 'FETCH_EMPLOYEES_STARTED';
export const SET_ALL_EMPLOYEERS = "SET_ALL_EMPLOYEERS";
export const FETCH_EMPLOYEESS_FAILURE = 'FETCH_EMPLOYEESS_FAILURE';
export const FETCH_WORKLOGS_STARTED = 'FETCH_WORKLOGS_STARTED';
export const SET_ALL_WORKLOGS = "SET_ALL_WORKLOGS";
export const FETCH_WORKLOGS_FAILURE = 'FETCH_WORKLOGS_FAILURE';
